name: Ping External Endpoint on Bot Suggestion

on:
  push:
    branches:
      - bot/suggestions

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Perform GET request to external service
        run: |
          echo "Triggering GET request to https://www.example.com..."
          curl -v https://www.example.com
